// gowinsvc project types.go
package gowinsvc

// ServiceObject
type ServiceObject struct {
	serviceName          string
	serviceStatusHandle  SERVICE_STATUS_HANDLE
	currentServiceStatus SERVICE_STATUS
	serviceInterface     Service
	serviceExit          chan bool
}

type Service interface {
	Serve(serviceExit <-chan bool)
}

// Service Type
const (
	SERVICE_KERNEL_DRIVER     = 0x00000001
	SERVICE_WIN32_OWN_PROCESS = 0x00000010
)

// Service State
const (
	SERVICE_STOPPED = iota + 1
	SERVICE_START_PENDING
	SERVICE_STOP_PENDING
	SERVICE_RUNNING
	SERVICE_CONTINUE_PENDING
	SERVICE_PAUSE_PENDING
	SERVICE_PAUSED
)

// Service Control
const (
	SERVICE_CONTROL_STOP = iota + 1
	SERVICE_CONTROL_PAUSE
	SERVICE_CONTROL_CONTINUE
	SERVICE_CONTROL_INTERROGATE
	SERVICE_CONTROL_SHUTDOWN
	SERVICE_CONTROL_PARAMCHANGE
	SERVICE_CONTROL_NETBINDADD
	SERVICE_CONTROL_NETBINDREMOVE
	SERVICE_CONTROL_NETBINDENABLE
	SERVICE_CONTROL_NETBINDDISABLE
	SERVICE_CONTROL_DEVICEEVENT
	SERVICE_CONTROL_HARDWAREPROFILECHANGE
	SERVICE_CONTROL_POWEREVENT
	SERVICE_CONTROL_SESSIONCHANGE
	SERVICE_CONTROL_PRESHUTDOWN
	SERVICE_CONTROL_TIMECHANGE
	SERVICE_CONTROL_TRIGGEREVENT = 0x00000020
)

// Controls Accepted
const (
	SERVICE_ACCEPT_STOP                  = 0x00000001
	SERVICE_ACCEPT_PAUSE_CONTINUE        = 0x00000002
	SERVICE_ACCEPT_SHUTDOWN              = 0x00000004
	SERVICE_ACCEPT_PARAMCHANGE           = 0x00000008
	SERVICE_ACCEPT_NETBINDCHANGE         = 0x00000010
	SERVICE_ACCEPT_HARDWAREPROFILECHANGE = 0x00000020
	SERVICE_ACCEPT_POWEREVENT            = 0x00000040
	SERVICE_ACCEPT_SESSIONCHANGE         = 0x00000080
	SERVICE_ACCEPT_PRESHUTDOWN           = 0x00000100
	SERVICE_ACCEPT_TIMECHANGE            = 0x00000200
	SERVICE_ACCEPT_TRIGGEREVENT          = 0x00000400
)

// SERVICE_STATUS_HANDLE
type (
	SERVICE_STATUS_HANDLE uintptr
)

// SERVICE_TABLE_ENTRY
type SERVICE_TABLE_ENTRY struct {
	serviceName uintptr
	serviceProc uintptr
}

// SERVICE_STATUS
type SERVICE_STATUS struct {
	serviceType             uint32
	currentState            uint32
	controlsAccepted        uint32
	win32ExitCode           uint32
	serviceSpecificExitCode uint32
	checkPoint              uint32
	waitHint                uint32
}
